version: '3.4'

services:
  master-new-api-0:
    image: fandeyi/new-api:20241216
    container_name: master-new-api-0
    command: --log-dir /app/logs
    ports:
      - "4000:3000"
    volumes:
      - ./master-new-api-0/data:/data
      - ./master-new-api-0/logs:/app/logs
    environment:
      - SQL_DSN=new-api:kwanjmjdZSBEYis4@tcp(172.17.0.1:3306)/new-api?parseTime=true
      - LOG_SQL_DSN=log-db:RKMDBwnc37ntMCLY@tcp(172.17.0.1:3306)/log-db?parseTime=true
      - REDIS_CONN_STRING=redis://172.17.0.1:6379/0
      - TZ=Asia/Shanghai
      - SESSION_SECRET=8285bba413e770fe9620f1bf9b40d44e
      - NODE_TYPE=master
      - SYNC_FREQUENCY=60
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  slave-new-api-1:
    image: fandeyi/new-api:20241216
    container_name: slave-new-api-1
    command: --log-dir /app/logs
    ports:
      - "4001:3000"
    volumes:
      - ./slave-new-api-1/data:/data
      - ./slave-new-api-1/logs:/app/logs
    environment:
      - SQL_DSN=new-api:kwanjmjdZSBEYis4@tcp(172.17.0.1:3306)/new-api?parseTime=true
      - LOG_SQL_DSN=log-db:RKMDBwnc37ntMCLY@tcp(172.17.0.1:3306)/log-db?parseTime=true
      - REDIS_CONN_STRING=redis://172.17.0.1:6379/0
      - TZ=Asia/Shanghai
      - SESSION_SECRET=8285bba413e770fe9620f1bf9b40d44e
      - NODE_TYPE=slave
      - SYNC_FREQUENCY=60
      - FRONTEND_BASE_URL=https://api-front.fandeyi.com
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  slave-new-api-2:
    image: fandeyi/new-api:20241216
    container_name: slave-new-api-2
    command: --log-dir /app/logs
    ports:
      - "4002:3000"
    volumes:
      - ./slave-new-api-2/data:/data
      - ./slave-new-api-2/logs:/app/logs
    environment:
      - SQL_DSN=new-api:kwanjmjdZSBEYis4@tcp(172.17.0.1:3306)/new-api?parseTime=true
      - LOG_SQL_DSN=log-db:RKMDBwnc37ntMCLY@tcp(172.17.0.1:3306)/log-db?parseTime=true
      - REDIS_CONN_STRING=redis://172.17.0.1:6379/0
      - TZ=Asia/Shanghai
      - SESSION_SECRET=8285bba413e770fe9620f1bf9b40d44e
      - NODE_TYPE=slave
      - SYNC_FREQUENCY=60
      - FRONTEND_BASE_URL=https://api-front.fandeyi.com
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  slave-new-api-3:
    image: fandeyi/new-api:20241216
    container_name: slave-new-api-3
    command: --log-dir /app/logs
    ports:
      - "4003:3000"
    volumes:
      - ./slave-new-api-3/data:/data
      - ./slave-new-api-3/logs:/app/logs
    environment:
      - SQL_DSN=new-api:kwanjmjdZSBEYis4@tcp(172.17.0.1:3306)/new-api?parseTime=true
      - LOG_SQL_DSN=log-db:RKMDBwnc37ntMCLY@tcp(172.17.0.1:3306)/log-db?parseTime=true
      - REDIS_CONN_STRING=redis://172.17.0.1:6379/0
      - TZ=Asia/Shanghai
      - SESSION_SECRET=8285bba413e770fe9620f1bf9b40d44e
      - NODE_TYPE=slave
      - SYNC_FREQUENCY=60
      - FRONTEND_BASE_URL=https://api-front.fandeyi.com
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always